version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=053622233369.dkr.ecr.us-east-2.amazonaws.com/nodejspoc
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  $REPOSITORY_URI:$IMAGE_TAG
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag  $REPOSITORY_URI:$IMAGE_TAG  $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
